### ISSUE TITLE
Update has broken the usage of Grocy while using the external port

### ISSUE THREAD

**Issue by akacruel** [hassio-addons/addon-grocy#208]
# Problem/Motivation

After update to 0.15.0 there is no way to use Grocy (Grocy is only available for admin with Ingress)

# Expected behavior

Work normally addon

# Actual behavior

All entities in database are missing

# Steps to reproduce

Update to 0.15.0, try to use any external port.
When I chose any external port which can be specified on the Addon Configuration page under the Network section, all entities in database are missing.

# Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

# logs:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-grocy: applying... 
[fix-attrs.d] 01-grocy: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Grocy
 ERP beyond your fridge! A groceries & household management solution for your home
-----------------------------------------------------------
 Add-on version: 0.15.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster) (amd64 / qemux86-64)
 Home Assistant Core: 2021.7.3
 Home Assistant Supervisor: 2021.06.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] grocy.sh: executing... 
[21:15:16] DEBUG: Symlinking data directory to persistent storage location...
[21:15:16] INFO: Patching Grocy to fix relative URL handling...
patching file views/layout/default.blade.php
Hunk #1 succeeded at 88 with fuzz 2 (offset 1 line).
[cont-init.d] grocy.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] php-fpm.sh: executing... 
[cont-init.d] php-fpm.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:15:17] INFO: Starting PHP-FPM...
[21:15:19] INFO: Starting NGinx....

**Comment by andreheuer** [comment]
Hi all,
I can confirm this behaviour. Same for me after upgrading to 0.15.

I noticed the following JS errors in my browser when opening grocy via the external port:
![image](https://user-images.githubusercontent.com/10393020/126618953-994313dc-da1c-445b-9872-22c8a136c276.png)

Looks like that some JS files were not found and thats why the data cannot be loaded.

BR
André

**Comment by jofotoo** [comment]
Noticing the same

**Comment by RubenKelevra** [comment]
I can confirm this issue

**Comment by RubenKelevra** [comment]
I can confirm this issue. @frenck are you working on a fix or is this an upstream issue?

**Comment by llewy** [comment]
I get those same errors when opening through Ingress. Something with the BASE_URL I presume.

**Comment by schoki1** [comment]
Here same issue, since upgrade to 0.15.0 access via external port is not possible see any entities anymore :-(

**Comment by RubenKelevra** [comment]
What's up with the delay @frenck? 🤔

**Comment by HydrelioxGitHub** [comment]
Same issue here.

**Comment by andreheuer** [comment]
Hi @RubenKelevra, @frenck,
any update here? This issue also blocks the usage of mobile apps for grocy, like grocy mobile :-(
BR
André

**Comment by RubenKelevra** [comment]
> Hi @RubenKelevra, @frenck,
> any update here? This issue also blocks the usage of mobile apps for grocy, like grocy mobile :-(
> BR
> André

I don't have no inside here. It's just a bit frustrating that I can't update, every time I look on the supervisor page 😂

**Comment by xBourner** [comment]
Having the same issue. Also ingress is having a bug while adding something from pruchase view.
The workaround for this is to open another port but this fix is also broken. :D

So there is no real way to get it running under Home Assistant. Could HA communicate with grocy if grocy will run in a docker container? is this working with the HACS integration?

**Comment by Mills79** [comment]
I'm also still being affected by this issue

**Comment by Jolly-Roger82** [comment]
I'm having the same issues. I installed Grocy, tried to scan the QR code with the Grocy ndroid App (support for 3.1.1) but it sais API invalid.

So i set port 9192, restart Grocy, go to my hass_IP:9192 settings API keys - No keys show, even when i make a new API QR code. 

They both show when i acces grocy via ingress, but still the API does not work for my grocy app.

In addition to this: My ingress masterdata is not in sync with the 9192 masterdata.

**Comment by Seechay** [comment]
I am having the same issues. It causes problems with Barcode Buddy as well.

**Comment by alpdmrel** [comment]
I can't acces to Grocy via port as well.

**Comment by mshuflin** [comment]
I can access grocy using its external url, but when I try to save a change to a product, I get an NS_ERROR_DOM_BAD_URI
and it looks like it is trying to do a put request to 
https://grocy.myurl.comhttps//grocy.myurl.com/api/objects/products/188

Seems to be a problem with the base URL

**Comment by MrMEEE** [comment]
Confirming the issue here

**Comment by RubenKelevra** [comment]
@frenck is this add-on still supported?

**Comment by frenck** [comment]
It's still being worked on, but you could see that if you looked at the commits

**Comment by MrMEEE** [comment]
Do you know when these fixes will be in a release?

**Comment by HydrelioxGitHub** [comment]
It seems that @frenck still handle this repository. I don't want to reveal anything personal but on his Twitter account, he had mentioned that he had health issues. 
So it's understandable that update are not published as quickly as before.
Grocy had several update since the last release of the addon in the past summer. I hope that if there is a new release that will be with the last Grocy version also.

Sorry for my English. And @frenck if I wrote anything wrong I will delete it as soon as you ask.

**Comment by frenck** [comment]
I am doing fine now :) busy as hell :)

**Comment by Sh8dyDan** [comment]
I'm having similar issues.

If I access grocy at http://homeassistant.local:8123/a0d7b954_grocy/dashboard everything works.

![03](https://user-images.githubusercontent.com/59207907/143793993-02e3f30d-9f69-4358-99c4-9902dc2e54a9.jpg)

If I access grocy at http://homeassistant.local:9283/products database is empty and nothing can be added.

![04](https://user-images.githubusercontent.com/59207907/143794031-67a5c4a7-1af4-4348-ae63-7e012888ca3b.jpg)

Chrome browser Console shows

![11](https://user-images.githubusercontent.com/59207907/143796714-8c3d49a0-3eb0-4455-8778-891efc354c21.jpg)

If I access grocy at https://grocy.mydomain.com/products database is present.

![05](https://user-images.githubusercontent.com/59207907/143794313-1142c9f2-5e20-423b-b0ad-c8e30252764f.jpg)

If I access grocy at http://homeassistant.local:8123/a0d7b954_grocy/dashboard to add a purchase Quantity Unit is populated.

![01](https://user-images.githubusercontent.com/59207907/143794775-2c5f60a3-2faa-432a-bc52-b758001909ea.jpg)

If I access grocy at https://grocy.mydomain.com/purchase Quantity Unit is empty.

![02](https://user-images.githubusercontent.com/59207907/143794635-c1ba7241-7329-4297-b35b-c4d0ef816106.jpg)

Chrome browser Console shows

![10](https://user-images.githubusercontent.com/59207907/143796576-5d344fa1-b99e-49d8-b2e4-c8e4ad10216a.jpg)

I hope this came across clear. I do appreciate all the work you guys put into this. Truly amazing.

Thank you

**Comment by Mills79** [comment]
Is their anyone that can explain to us how to apply these fixes.

**Comment by Jolly-Roger82** [comment]
I was messing around with Grocy and Barcode Buddy just now and sadly I had to see that it still does not work as could be expected.

Grocy is not usable right now when using barcode buddy or pantry party for instance.

**Comment by frenck** [comment]
Fixed in #267

**Comment by Mills79** [comment]
I've upgraded to 0.16.0 but I still can't see any products when accessing grocy via the local ip address

**Comment by Jolly-Roger82** [comment]
I've upgraded to version 0.16.0 as well and all works fine like it should. Working on local an the Ingress version (in hass itsself) and the web-interface version (port 9192) are in sync now. I can work with API keys and i can see all my masterdata in both versions. 

Thank's @frenck this did the trick!

**Comment by akacruel** [comment]
> I've upgraded to 0.16.0 but I still can't see any products when accessing grocy via the local ip address
> 
> Add-on version: 0.16.0 You are running the latest version of this add-on. System: Home Assistant OS 7.0 (amd64 / generic-x86-64) Home Assistant Core: 2021.12.3 Home Assistant Supervisor: 2021.12.2 ----------------------------------------------------------
> 
> * Please, share the above information when looking for help or support in, e.g., GitHub, forums or the Discord chat. -----------------------------------------------------------
>   [cont-init.d] 00-banner.sh: exited 0.
>   [cont-init.d] 01-log-level.sh: executing...
>   [cont-init.d] 01-log-level.sh: exited 0.
>   [cont-init.d] grocy.sh: executing...
>   [21:30:02] INFO: Patching Grocy to fix relative URL handling...
>   patching file views/layout/default.blade.php
>   patch unexpectedly ends in middle of line
>   patch: **** malformed patch at line 15:
>   [cont-init.d] grocy.sh: exited 0.
>   [cont-init.d] nginx.sh: executing...
>   [cont-init.d] nginx.sh: exited 0.
>   [cont-init.d] php-fpm.sh: executing...
>   [cont-init.d] php-fpm.sh: exited 0.
>   [cont-init.d] done.
>   [services.d] starting services
>   [services.d] done.
>   [21:30:05] INFO: Starting PHP-FPM...
>   [21:30:08] INFO: Starting NGinx....

similarly
