### ISSUE TITLE
Can not  add item in the Location, Stores, Product groups, Batteries, Task categories, Userfields, Userentities.

### ISSUE THREAD

**Issue by ngnxuanhoa** [hassio-addons/addon-grocy#481]
Hello,
I have grocy installed on a home assistant instance as an add-on
Not working when to add item in the Location, Stores, Product groups, Batteries, Task categories, Userfields, Userentities.

 Add-on: Grocy
 ERP beyond your fridge! A groceries & household management solution for your home
-----------------------------------------------------------
 Add-on version: 0.24.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 15.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2025.3.4
 Home Assistant Supervisor: 2025.03.3

i try the demo link so everything working fine.

Thank you

**Comment by YazawaMasaki** [comment]
Same here, last update seems to broke a lot of [add] buttons. One workaround is to right click [add] button, open in new tab and add stuff there. Currently have 2 HA install running. One upgraded from 0.23.0, another one with fresh installed 0.24.0, both experiencing same issue.

**Comment by zeg064** [comment]
Same for me. I've just installed this add-on for the first time.
Version 0.24.0

When clicking "Add" button in tasks (for example) no action is taken. Right-click workaround as noted above works.

**Comment by MrAtari1040ST** [comment]
Just installed grocy, can add products, but not the items mentioned in this issue. Looks like it won't open a popup window as I saw in the demo. That might be the reason it does work when opening link in another tab.

**Comment by RALFISBORN** [comment]
same Problem in v0.24.0

**Comment by coaster3000** [comment]
This is technically a problem with I frames and a change in grocy with the last stable release of the addon.

Dialogs that open with buttons such as the add button (described in this issue) do not open. A workaround is to open grocy as it's own window without being in the home assistant iframe. You can do this by right clicking the grocy logo and opening a new tab (most cases)

Then iframe interactions will function as normal.

Grocy did release an update addressing this, which was merged into the edge build of the addon but has yet to be released.

That pull request is located here https://github.com/hassio-addons/addon-grocy/pull/478

**Comment by WoosterInitiative** [comment]
It's been fixed by Grocy, the add-on just needs to use the new version.

**Comment by ngnxuanhoa** [comment]
> It's been fixed by Grocy, the add-on just needs to use the new version.

i see the lastest version still is v0.24.0

**Comment by zunami** [comment]
i have the same Problem 0.24.0

**Comment by strikeir13** [comment]
It's not listed in the issue title, but this also affects Chores. The only way I could get to work was opening up grocy directly, meaning looking up which port it was using in the HA add-on configuration and then going to [HA IP]:9192. Once I did that, I could add chores normally.

Looking forward to the update.

**Comment by xpucu** [comment]
Can confirm that it is still broken as of the latest HA/Grocy add-on version. 

Tested with Chrome and Firefox on Mac Sequoia 15.3.2 (24D81)

Browser debug/error:

```
Error: Orphaned iframed web-client-content-script.js:2:304811
```

The workaround still works - to use one of these options:

<img width="496" alt="Image" src="https://github.com/user-attachments/assets/450b5ccf-0eaf-428d-8f1f-30a68e00ffef" />


Configuration:

```
culture: en
currency: USD
entry_page: stock
features:
  batteries: true
  calendar: true
  chores: true
  equipment: true
  recipes: true
  shoppinglist: true
  stock: true
  tasks: true
tweaks:
  chores_assignment: true
  multiple_shopping_lists: true
  stock_best_before_date_tracking: true
  stock_location_tracking: true
  stock_price_tracking: true
  stock_product_freezing: true
  stock_product_opened_tracking: true
  stock_count_opened_products_against_minimum_stock_amount: true
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
grocy_ingress_user: ""
```

Logs:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Grocy
 ERP beyond your fridge! A groceries & household management solution for your home
-----------------------------------------------------------
 Add-on version: 0.24.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 15.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2025.5.1
 Home Assistant Supervisor: 2025.05.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-php-fpm: starting
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-grocy: starting
[00:36:21] INFO: Patching Grocy to fix relative URL handling...
patching file views/layout/default.blade.php
Hunk #1 succeeded at 96 (offset 2 lines).
s6-rc: info: service init-grocy successfully started
s6-rc: info: service init-nginx successfully started
s6-rc: info: service init-php-fpm successfully started
s6-rc: info: service php-fpm: starting
s6-rc: info: service php-fpm successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
[00:36:22] INFO: Starting PHP-FPM...
s6-rc: info: service legacy-services successfully started
[00:36:24] INFO: Starting NGinx....
[00:36:24] INFO: Starting NGinx....
```

**Comment by gordenHA2** [comment]
confirming the issue about maintaining certain master data, won't open the corresponding window unless 'open in new tab' was choosen

**Comment by gordenHA2** [comment]
since issue seems to be known and solved by 4.4.2, why isn't that released as HA addon in the mean time? What is the blocking topic?

**Comment by villakarow** [comment]
This is still an issue for HA addon

**Comment by Martin98-MD** [comment]
Still cant add Locations, Stores, Product groups, Batteries, Task catagories, Userfields, Userentities

**Comment by thunfisch987** [comment]
See https://github.com/grocy/grocy/issues/2783#issuecomment-3135294455

If you really want to use the HA addon instead of a separate installation then either install from a fork of this repo that updated it (i won't recommend one, please check that nothing changed except the version so you're not installing malware or something)
Or fork it yourself and try to apply for the official addon

**Comment by villakarow** [comment]
> See [grocy/grocy#2783 (comment)](https://github.com/grocy/grocy/issues/2783#issuecomment-3135294455)
> 
> If you really want to use the HA addon instead of a separate installation then either install from a fork of this repo that updated it (i won't recommend one, please check that nothing changed except the version so you're not installing malware or something) Or fork it yourself and try to apply for the official addon

Hm, thanks for this proposal. As you said it might be risky. And I do not know how to install a fork.

**Comment by thunfisch987** [comment]
https://github.com/mechmyday/addon-grocy seems to have done it
@mechmyday could you explain how you added it?

**Comment by tiiiser86** [comment]
> Still cant add Locations, Stores, Product groups, Batteries, Task catagories, Userfields, Userentities

I have the same issues. Do you have some advice?  I would like to use the add on in my HA Set up. Thx

**Comment by thunfisch987** [comment]
see my comment https://github.com/hassio-addons/addon-grocy/issues/481#issuecomment-3233370512
